name: nsc2026
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py312h6b91d65_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - arrow=1.4.0=pyhcf101f3_0
  - astroid=4.0.3=py312h2e8e312_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - asyncssh=2.21.1=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - autopep8=2.0.4=pyhd8ed1ab_0
  - aws-c-auth=0.9.3=h2970c50_0
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.1=hcb3a2da_9
  - aws-c-event-stream=0.5.7=ha388e84_1
  - aws-c-http=0.10.7=hc678f4a_5
  - aws-c-io=0.23.3=h0d5b9f9_5
  - aws-c-mqtt=0.13.3=hfa314fa_11
  - aws-c-s3=0.11.3=ha659bf3_1
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.7=hcb3a2da_5
  - aws-crt-cpp=0.35.4=hca034e6_0
  - aws-sdk-cpp=1.11.606=hac16450_10
  - babel=2.18.0=pyhcf101f3_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhcf101f3_2
  - backports.zstd=1.3.0=py312h06d0912_0
  - bcrypt=5.0.0=py312hdabe01f_1
  - beautifulsoup4=4.14.3=pyha770c72_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - black=26.1.0=pyh866005b_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - bokeh=3.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py312hc6d9e41_1
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - cattrs=25.3.0=pyhd8ed1ab_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py312he06e257_1
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312h78d62e6_4
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - coverage=7.13.3=py312h05f76fc_0
  - cpython=3.12.12=py312hd8ed1ab_2
  - cryptography=46.0.4=py312h232196e_0
  - cycler=0.12.1=pyhcf101f3_2
  - cytoolz=1.1.0=py312he06e257_1
  - dask=2026.1.2=pyhcf101f3_0
  - dask-core=2026.1.2=pyhcf101f3_0
  - debugpy=1.8.20=py312ha1a9051_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_1
  - diff-match-patch=20241021=pyhd8ed1ab_1
  - dill=0.4.1=pyhcf101f3_0
  - distributed=2026.1.2=pyhcf101f3_0
  - docstring-to-markdown=0.17=pyhe01879c_0
  - docutils=0.22.4=pyhd8ed1ab_0
  - double-conversion=3.4.0=hac47afa_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - flake8=7.1.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py312h05f76fc_0
  - freetype=2.14.1=h57928b3_0
  - frozenlist=1.7.0=py312hfdf67e6_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - fzf=0.67.0=hb13f615_0
  - glib=2.86.3=h19e2e61_0
  - glib-tools=2.86.3=he647baa_0
  - graphite2=1.3.14=hac47afa_2
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h5f2951f_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - inflection=0.5.1=pyhd8ed1ab_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.31.0=pyh6dadd2b_0
  - ipython=9.10.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isort=7.0.0=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhcf101f3_3
  - jaraco.context=6.1.0=pyhcf101f3_0
  - jaraco.functools=4.4.0=pyhcf101f3_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jellyfish=1.2.1=py312hb0142fd_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - keyring=25.7.0=pyh7428d3b_0
  - kiwisolver=1.4.9=py312h78d62e6_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.18=hf2c6c5f_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=23.0.0=hcf7e2ff_1_cpu
  - libarrow-acero=23.0.0=h7d8d6a5_1_cpu
  - libarrow-compute=23.0.0=h2db994a_1_cpu
  - libarrow-dataset=23.0.0=h7d8d6a5_1_cpu
  - libarrow-substrait=23.0.0=hf865cc0_1_cpu
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.8=default_ha2db4b5_3
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.18.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_17
  - libglib=2.86.3=h0c9aed9_0
  - libgomp=15.2.0=h8ee18e1_17
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libogg=1.3.5=h2466b09_1
  - libparquet=23.0.0=h7051d1f_1_cpu
  - libpng=1.6.54=h7351971_0
  - libprotobuf=6.31.1=hdcda5b4_4
  - libre2-11=2025.11.05=h0eb2380_0
  - libsodium=1.0.20=hc70643c_0
  - libspatialindex=2.1.0=h518811d_0
  - libsqlite=3.51.2=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h8f73337_1
  - libutf8proc=2.11.3=hb980946_0
  - libvorbis=1.3.7=h5112557_2
  - libvulkan-loader=1.4.341.0=h477610d_0
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - llvmlite=0.46.0=py312hdb9728c_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lsprotocol=2025.0.0=pyhe01879c_0
  - lz4=4.4.5=py312hc3c93f3_1
  - lz4-c=1.10.0=h2466b09_1
  - m2-base=2022.06.1=hc364b38_6
  - m2-bash=5.2.037.2=hc364b38_6
  - m2-bash-completion=2.16.0.1=hc364b38_6
  - m2-brotli=1.1.0.2=hc364b38_6
  - m2-bsdtar=3.7.9.1=hc364b38_6
  - m2-bzip2=1.0.8.4=hc364b38_6
  - m2-ca-certificates=20241223.1=hc364b38_6
  - m2-conda-epoch=20250515=0_x86_64
  - m2-coreutils=8.32.5=hc364b38_6
  - m2-curl=8.9.1.1=hc364b38_6
  - m2-dash=0.5.12.1=hc364b38_6
  - m2-file=5.46.2=hc364b38_6
  - m2-filesystem=2025.02.23.1=hc364b38_10
  - m2-findutils=4.9.0.3=hc364b38_6
  - m2-gawk=5.3.2.1=hc364b38_6
  - m2-gcc-libs=13.3.0.1=hc364b38_6
  - m2-getent=2.18.90.5=hc364b38_6
  - m2-gmp=6.3.0.1=hc364b38_6
  - m2-grep=1!3.0.7=hc364b38_6
  - m2-gzip=1.14.1=hc364b38_6
  - m2-heimdal-libs=7.8.0.5=hc364b38_6
  - m2-inetutils=2.5.2=hc364b38_6
  - m2-info=7.2.1=hc364b38_6
  - m2-less=668.1=hc364b38_6
  - m2-libargp=20241207.1=hc364b38_6
  - m2-libbz2=1.0.8.4=hc364b38_6
  - m2-libcurl=8.9.1.1=hc364b38_6
  - m2-libdb=6.2.32.5=hc364b38_6
  - m2-libedit=20240808_3.1.1=hc364b38_6
  - m2-libexpat=2.7.1.1=hc364b38_6
  - m2-libffi=3.4.8.1=hc364b38_6
  - m2-libgnutls=3.8.9.1=hc364b38_6
  - m2-libhogweed=3.9.1.1=hc364b38_6
  - m2-libiconv=1.18.1=hc364b38_6
  - m2-libidn2=2.3.8.1=hc364b38_6
  - m2-libintl=0.22.5.1=hc364b38_6
  - m2-liblz4=1.9.4.1=hc364b38_6
  - m2-liblzma=5.8.1.1=hc364b38_6
  - m2-libnettle=3.9.1.1=hc364b38_6
  - m2-libnghttp2=1.65.0.1=hc364b38_6
  - m2-libopenssl=3.5.0.1=hc364b38_6
  - m2-libp11-kit=0.25.5.2=hc364b38_6
  - m2-libpcre=8.45.5=hc364b38_6
  - m2-libpcre2_8=10.45.1=hc364b38_6
  - m2-libpsl=0.21.5.2=hc364b38_6
  - m2-libreadline=8.2.013.1=hc364b38_6
  - m2-libsqlite=3.49.1.2=hc364b38_6
  - m2-libssh2=1.11.1.1=hc364b38_6
  - m2-libtasn1=4.20.0.1=hc364b38_6
  - m2-libunistring=1.3.1=hc364b38_6
  - m2-libutil-linux=2.40.2.2=hc364b38_6
  - m2-libxcrypt=4.4.38.1=hc364b38_6
  - m2-libzstd=1.5.7.1=hc364b38_6
  - m2-mintty=1!3.7.8.1=hc364b38_6
  - m2-mpfr=4.2.2.1=hc364b38_6
  - m2-msys2-keyring=1!20250214.1=hc364b38_6
  - m2-msys2-launcher=1.5.3=hc364b38_6
  - m2-msys2-runtime=3.6.1.4=hc364b38_6
  - m2-nano=8.4.1=hc364b38_6
  - m2-ncurses=6.5.20240831.2=hc364b38_6
  - m2-openssl=3.5.0.1=hc364b38_6
  - m2-p11-kit=0.25.5.2=hc364b38_6
  - m2-rebase=4.5.0.4=hc364b38_6
  - m2-sed=4.9.1=hc364b38_6
  - m2-tar=1.35.2=hc364b38_6
  - m2-time=1.9.3=hc364b38_6
  - m2-tzcode=2025b.1=hc364b38_6
  - m2-util-linux=2.40.2.2=hc364b38_6
  - m2-wget=1.25.0.1=hc364b38_6
  - m2-which=2.23.4=hc364b38_6
  - m2-zlib=1.3.1.1=hc364b38_6
  - m2-zstd=1.5.7.1=hc364b38_6
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h05f76fc_0
  - matplotlib=3.10.8=py312h2e8e312_0
  - matplotlib-base=3.10.8=py312h0ebf65c_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.2.0=pyhcf101f3_0
  - mkl=2025.3.0=hac47afa_455
  - more-itertools=10.8.0=pyhcf101f3_1
  - msgpack-python=1.1.2=py312hf90b1b7_1
  - multidict=6.7.0=py312h05f76fc_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - narwhals=2.16.0=pyhcf101f3_0
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert=7.17.0=h14065e2_0
  - nbconvert-core=7.17.0=pyhcf101f3_0
  - nbconvert-pandoc=7.17.0=hc3985f0_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numba=0.63.1=py312h560f1c9_0
  - numpy=2.3.5=py312ha72d056_1
  - numpydoc=1.10.0=pyhcf101f3_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.1=hf411b9b_1
  - orc=2.2.2=hbd3206f_0
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py312h95189c4_0
  - pandoc=3.9=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pathspec=1.0.4=pyhd8ed1ab_0
  - pcre2=10.47=hd2b5f0e_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.1.0=py312h31f0997_0
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - ply=3.11=pyhd8ed1ab_3
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py312h31fea79_0
  - psutil=7.2.2=py312he5662c2_0
  - pthread-stubs=0.4=h0e40799_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=23.0.0=py312h2e8e312_0
  - pyarrow-core=23.0.0=py312h85419b5_0_cpu
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygithub=2.8.1=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.11.0=pyhd8ed1ab_0
  - pylint=4.0.4=pyhcf101f3_0
  - pylint-venv=3.0.4=pyhd8ed1ab_1
  - pyls-spyder=0.4.0=pyhd8ed1ab_1
  - pynacl=1.6.2=py312he06e257_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyqt=5.15.11=py312h7eb3e20_2
  - pyqt5-sip=12.17.0=py312hbb81ca0_2
  - pyqtwebengine=5.15.11=py312hffa3973_2
  - pyside6=6.10.1=py312h0c8bdd4_0
  - pysocks=1.7.1=pyh09c184e_7
  - pytest=9.0.2=pyhcf101f3_0
  - pytest-cov=7.0.0=pyhcf101f3_1
  - python=3.12.12=h0159041_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_2
  - python-gssapi=1.11.1=py312hd572b79_0
  - python-lsp-black=2.0.0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhff2d567_1
  - python-lsp-ruff=2.3.0=pyhcf101f3_0
  - python-lsp-server=1.14.0=pyh332efcf_0
  - python-lsp-server-base=1.14.0=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytokens=0.4.1=py312he5662c2_0
  - pytoolconfig=1.2.5=pyhd8ed1ab_1
  - pytz=2025.2=pyhd8ed1ab_0
  - pyuca=1.2=pyhd8ed1ab_2
  - pywin32=311=py312h829343e_1
  - pywin32-ctypes=0.2.3=py312h2e8e312_3
  - pyyaml=6.0.3=py312h05f76fc_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - qdarkstyle=3.2.3=pyhd8ed1ab_1
  - qhull=2020.2=hc790b64_5
  - qstylizer=0.2.4=pyhff2d567_0
  - qt-main=5.15.15=hb098fff_6
  - qt-webengine=5.15.15=h087ee03_1
  - qt6-main=6.10.1=hf1bda90_3
  - qtawesome=1.4.1=pyh9208f05_0
  - qtconsole=5.7.0=pyhd8ed1ab_0
  - qtconsole-base=5.7.0=pyha770c72_0
  - qtpy=2.4.3=pyhd8ed1ab_1
  - re2=2025.11.05=ha104f34_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rich=14.3.2=pyhcf101f3_0
  - roman-numerals=4.1.0=pyhd8ed1ab_0
  - rope=1.14.0=pyhd8ed1ab_0
  - rpds-py=0.30.0=py312hdabe01f_0
  - rtree=1.4.1=pyh11ca60a_0
  - ruff=0.15.0=h213852a_0
  - scipy=1.17.0=py312h9b3c559_1
  - setuptools=80.10.2=pyh332efcf_0
  - sip=6.10.0=py312hbb81ca0_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - sphinx=9.1.0=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - spyder=6.1.2=hd8ed1ab_0
  - spyder-base=6.1.2=py312h2e8e312_0
  - spyder-kernels=3.1.2=win_pyh7428d3b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - superqt=0.7.8=pyh9208f05_0
  - tbb=2022.3.0=h3155e25_2
  - tblib=3.2.2=pyhcf101f3_0
  - text-unidecode=1.3=pyhd8ed1ab_2
  - textdistance=4.6.3=pyhd8ed1ab_1
  - three-merge=0.1.1=pyhd8ed1ab_1
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.13=h6ed50ae_3
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.4.0=pyhcf101f3_0
  - tomlkit=0.14.0=pyha770c72_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py312he06e257_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - ujson=5.11.0=py312ha1a9051_1
  - unicodedata2=17.0.0=py312he06e257_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - watchdog=6.0.0=py312h2e8e312_2
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - whatthepatch=1.0.7=pyhd8ed1ab_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=2.1.1=py312he06e257_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h6a83c73_3
  - yapf=0.43.0=pyhd8ed1ab_1
  - yarl=1.22.0=py312h05f76fc_0
  - zeromq=4.3.5=h5bddc39_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.3=h0261ad2_1
  - zstd=1.5.7=h534d264_6

prefix: "C:\\Users\\User\\miniforge3\\envs\\nsc2026"
